# Generated by Django 2.1.7 on 2019-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail_description', models.CharField(max_length=5000)),
                ('short_description', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'video_detail',
            },
        ),
    ]
